#!/bin/bash                                                                                                                                                                                                                                                             
# Install openexr from source. Because `pip install tensorflow_graphics` fails.                                                                                                                                                                                         
echo "Installing openexr from source"                                                                                                                                                                                                                                    
wget https://github.com/AcademySoftwareFoundation/openexr/archive/v2.5.5.tar.gz                                                                                                                                                                                         
tar -xvf v2.5.5.tar.gz                                                                                                                                                                                                                                                  
cd openexr-2.5.5/                                                                                                                                                                                                                                                       
mkdir build                                                                                                                                                                                                                                                             
cd build                                                                                                                                                                                                                                                                
cmake ../                                                                                                                                                                                                                                                               
make                                                                                                                                                                                                                                                                    
make install                                                                                                                                                                                                                                                            
cd ../../  # pop back to starting directory.                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                        
# Install TensorFlow Graphics. For OSX.                                                                                                                                                                                                                                 
echo "Installing TensorFlow Graphics from source."                                                                                                                                                                                                                      
git clone https://github.com/tensorflow/graphics.git                                                                                                                                                                                                                    
cd graphics                                                                                                                                                                                                                                                             
# XXX MANUAL: Comment out OpenEXR in requirements.txt XXX                                                                                                                                                                                                               
python setup.py sdist bdist_wheel   # Build pip pkg.                                                                                                                                                                                                                    
pip install --upgrade dist/*.whl                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                        
echo "All Done... check for errors."        